services:
  cgit:
    image: docker.io/memdmp/cgit:local-build
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - cgit_ssh:/etc/ssh:rw
      - ./cgit/repos:/var/lib/git:rw
    ports:
      - 127.0.0.1:18080:80
      - 127.0.0.1:12222:22
    env_file:
      - .env

volumes:
  cgit_ssh:
  cgit_repos:
