[package]
name = "markdown-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.12.2"

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
